# Generated by Django 5.1.3 on 2024-11-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_products', '0002_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': 'ProductImages'},
        ),
        migrations.AddField(
            model_name='product',
            name='available_size',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
