# Generated by Django 5.1.3 on 2024-11-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_products', '0004_category_category_thubnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Products'},
        ),
    ]
