# Generated by Django 5.1.3 on 2024-12-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
